services:
  - type: web
    name: taller2-dash
    env: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    autoDeploy: true
